#!/usr/bin/env bash
# Create a .env for a private instance, with real secrets, once.
#
#   ./docker/first-run.sh you@example.com
#
# Refuses to overwrite an existing .env: regenerating FORGECAST_SECRET_KEY would
# invalidate every session cookie and every signed media URL, and regenerating
# FORGECAST_ENCRYPTION_KEY would make every stored provider key permanently
# undecryptable. Those are not recoverable from a backup of the database alone.

set -euo pipefail

EMAIL="${1:-}"
if [ -z "$EMAIL" ]; then
    echo "usage: $0 <owner-email>" >&2
    exit 64
fi

if [ -e .env ]; then
    echo ".env already exists — not touching it." >&2
    echo "Rotating the secret key logs you out and breaks existing media links;" >&2
    echo "rotating the encryption key makes stored provider keys unreadable." >&2
    exit 1
fi

PY=$(command -v python3 || command -v python)

SECRET=$("$PY" -c "import secrets; print(secrets.token_urlsafe(48))")
FERNET=$("$PY" -c "import base64, secrets; print(base64.urlsafe_b64encode(secrets.token_bytes(32)).decode())")
PASSWORD=$("$PY" -c "import secrets; print(secrets.token_urlsafe(18))")

cat > .env <<EOF
# Generated by docker/first-run.sh. Keep this file out of version control.
FORGECAST_SECRET_KEY=${SECRET}
FORGECAST_ENCRYPTION_KEY=${FERNET}

FORGECAST_DATABASE_URL=sqlite:////data/forgecast.db
FORGECAST_STORAGE_DIR=/data/storage
FORGECAST_BASE_URL=http://localhost:8000

# mock spends nothing and calls no provider. Switch to live once you have added keys.
FORGECAST_PROVIDER_MODE=mock

# Private instance: registration closed, one owner account.
FORGECAST_ALLOW_SIGNUP=false
FORGECAST_OWNER_EMAIL=${EMAIL}
FORGECAST_OWNER_PASSWORD=${PASSWORD}
FORGECAST_OWNER_GRANT=10000
FORGECAST_OWNER_CHANNEL=My Channel

# Loopback only. Front it with a proxy or a tunnel rather than opening this up.
FORGECAST_PUBLISH_ADDR=127.0.0.1
FORGECAST_FORWARDED_ALLOW_IPS=127.0.0.1

FORGECAST_WORKER_CONCURRENCY=2

# ---- provider keys (optional; each one is also settable per-user in the UI) ----
FORGECAST_ANTHROPIC_API_KEY=
FORGECAST_OPENAI_API_KEY=
FORGECAST_ELEVENLABS_API_KEY=
FORGECAST_FAL_KEY=
FORGECAST_TAVILY_API_KEY=
FORGECAST_BRAVE_API_KEY=
FORGECAST_YOUTUBE_CLIENT_ID=
FORGECAST_YOUTUBE_CLIENT_SECRET=
EOF

chmod 600 .env

cat <<EOF

Wrote .env (mode 600).

  owner     ${EMAIL}
  password  ${PASSWORD}

Write that password down now — it is stored in .env in plain text, which is fine for
a single-operator instance but means anyone with the file has your login. Change it
later with:

  docker compose run --rm app bootstrap --email ${EMAIL} \\
      --password 'a-new-long-password' --reset-password

Then start it:

  docker compose up -d
  open http://localhost:8000

EOF
